[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[colors.primary]
foreground = "#EBEEF9"
background = "#0D101B"

[colors.cursor]
text = "#EBEEF9"
cursor = "#FFFFFF"

[colors.normal]
black = "#000009"
blue = "#58B6CA"
cyan = "#8D84C6"
green = "#72CCAE"
magenta = "#6488C4"
red = "#BB4F6C"
white = "#858893"
yellow = "#C65E3D"

[colors.bright]
black = "#1F222D"
blue = "#8BE9FD"
cyan = "#C0B7F9"
green = "#A5FFE1"
magenta = "#97BBF7"
red = "#EE829F"
white = "#FFFFFF"
yellow = "#F99170"

[window.padding]
x = 20
y = 20
